# Generated by Django 5.2.9 on 2025-12-30 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("harassment", "Harassment"),
                            ("spam", "Spam"),
                            (
                                "religious_harassment",
                                "Religious Harassment / Disrespect",
                            ),
                            ("hate_speech", "Hate Speech"),
                            ("inappropriate_content", "Inappropriate Content"),
                            ("fake_profile", "Fake Profile"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Additional details about the report (optional)",
                        max_length=1000,
                    ),
                ),
                (
                    "handled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this report has been reviewed by a moderator",
                    ),
                ),
                (
                    "handled_at",
                    models.DateTimeField(
                        blank=True, help_text="When the report was handled", null=True
                    ),
                ),
                (
                    "moderator_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes from the moderator"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Moderator who handled this report",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_handled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reported_user",
                    models.ForeignKey(
                        help_text="User being reported",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        help_text="User who submitted the report",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["reporter", "-created_at"],
                        name="moderation__reporte_350be5_idx",
                    ),
                    models.Index(
                        fields=["reported_user", "-created_at"],
                        name="moderation__reporte_9007a7_idx",
                    ),
                    models.Index(
                        fields=["handled", "-created_at"],
                        name="moderation__handled_c92c03_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="moderation__created_6c20ed_idx"
                    ),
                ],
            },
        ),
    ]
