# Generated by Django 5.2.9 on 2025-12-30 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatThread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_message_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the last message sent in this thread",
                        null=True,
                    ),
                ),
                (
                    "user1",
                    models.ForeignKey(
                        help_text="First user in the thread (lower user ID)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_threads_as_user1",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user2",
                    models.ForeignKey(
                        help_text="Second user in the thread (higher user ID)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_threads_as_user2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_message_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Message content (max 2000 characters)",
                        max_length=2000,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the message was read by the recipient",
                        null=True,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.chatthread",
                    ),
                ),
            ],
            options={
                "ordering": ["sent_at"],
            },
        ),
        migrations.AddIndex(
            model_name="chatthread",
            index=models.Index(
                fields=["user1", "-last_message_at"],
                name="chat_chatth_user1_i_6294d6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatthread",
            index=models.Index(
                fields=["user2", "-last_message_at"],
                name="chat_chatth_user2_i_547fc0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatthread",
            index=models.Index(
                fields=["-last_message_at"], name="chat_chatth_last_me_9fab80_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="chatthread",
            constraint=models.UniqueConstraint(
                fields=("user1", "user2"), name="unique_chat_thread_pair"
            ),
        ),
        migrations.AddConstraint(
            model_name="chatthread",
            constraint=models.CheckConstraint(
                condition=models.Q(("user1__lt", models.F("user2"))),
                name="user1_less_than_user2",
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["thread", "sent_at"], name="chat_chatme_thread__d53411_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["thread", "read_at"], name="chat_chatme_thread__371b2c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["sender", "-sent_at"], name="chat_chatme_sender__e24abf_idx"
            ),
        ),
    ]
