# Generated by Django 5.2.9 on 2025-12-30 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("blocked", "Blocked"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the connection was accepted",
                        null=True,
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        help_text="User who initiated the connection",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        help_text="User who received the connection request",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["from_user", "status"],
                        name="connections_from_us_c3fa2d_idx",
                    ),
                    models.Index(
                        fields=["to_user", "status"],
                        name="connections_to_user_9f6d89_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="connections_status_94aad8_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("from_user", "to_user"), name="unique_connection_pair"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("from_user", models.F("to_user")), _negated=True
                        ),
                        name="no_self_connection",
                    ),
                ],
            },
        ),
    ]
