# Generated by Django 5.2.4 on 2025-12-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connections", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="connection",
            name="intro_message",
            field=models.TextField(
                blank=True,
                help_text="Optional intro message sent with connection request",
                max_length=200,
            ),
        ),
    ]
