# Generated by Django 5.2.9 on 2025-12-30 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IntentTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InterestTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("category", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=100)),
                ("bio", models.TextField(blank=True, max_length=500)),
                (
                    "pronouns",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("he_him", "He/Him"),
                            ("she_her", "She/Her"),
                            ("they_them", "They/Them"),
                            ("other", "Other"),
                            ("prefer_not_to_say", "Prefer not to say"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "age_bucket",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("18_24", "18–24"),
                            ("25_34", "25–34"),
                            ("35_44", "35–44"),
                            ("45_54", "45–54"),
                            ("55_plus", "55+"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "primary_language",
                    models.CharField(default="English", max_length=50),
                ),
                ("other_languages", models.JSONField(blank=True, default=list)),
                (
                    "faith",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("christian", "Christian"),
                            ("muslim", "Muslim"),
                            ("traditional", "Traditional / Spiritual"),
                            ("other", "Other"),
                            ("prefer_not_to_say", "Prefer not to say"),
                        ],
                        max_length=20,
                    ),
                ),
                ("faith_visible", models.BooleanField(default=False)),
                ("is_complete", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "intents",
                    models.ManyToManyField(
                        blank=True, related_name="profiles", to="profiles.intenttag"
                    ),
                ),
                (
                    "interests",
                    models.ManyToManyField(
                        blank=True, related_name="profiles", to="profiles.interesttag"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfilePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="profile_photos/%Y/%m/")),
                ("ordering_index", models.PositiveSmallIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["ordering_index"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "ordering_index"),
                        name="unique_photo_order_per_profile",
                    )
                ],
            },
        ),
    ]
