# Generated by Django 5.2.9 on 2025-12-30 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(default="Ghana", max_length=100)),
                (
                    "radius_km",
                    models.PositiveSmallIntegerField(
                        default=25, help_text="Search radius in km (5-50)"
                    ),
                ),
                (
                    "share_precision",
                    models.CharField(
                        choices=[
                            ("city_only", "City Only"),
                            ("approx", "Approximate"),
                            ("nearby", "Nearby Area"),
                        ],
                        default="approx",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_preference",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location Preference",
                "verbose_name_plural": "Location Preferences",
            },
        ),
        migrations.CreateModel(
            name="MatchingPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preferred_age_buckets", models.JSONField(blank=True, default=list)),
                ("available_mornings", models.BooleanField(default=False)),
                ("available_afternoons", models.BooleanField(default=False)),
                ("available_evenings", models.BooleanField(default=False)),
                ("available_weekdays", models.BooleanField(default=True)),
                ("available_weekends", models.BooleanField(default=True)),
                (
                    "faith_filter",
                    models.CharField(
                        choices=[
                            ("same_only", "Same faith only"),
                            ("open_to_all", "Open to all faiths"),
                            ("custom", "Custom (exclude specific)"),
                        ],
                        default="open_to_all",
                        max_length=20,
                    ),
                ),
                ("faith_exclude", models.JSONField(blank=True, default=list)),
                (
                    "visible",
                    models.BooleanField(
                        default=True, help_text="Show my profile in discovery"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matching_preference",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matching Preference",
                "verbose_name_plural": "Matching Preferences",
            },
        ),
    ]
